FROM nvidia/cuda:12.6.1-cudnn-devel-ubuntu20.04

ENV DEBIAN_FRONTEND noninteractive

# Установите несколько зависимостей системы
RUN apt-get -y update

RUN apt-get install -y git wget curl libgl1-mesa-glx libglib2.0-0

RUN rm -rf /var/lib/apt/lists/*

# Установите pip и обновите его
RUN apt-get -y update

RUN apt-get install -y python3-pip

RUN pip3 install --upgrade pip


RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu111

RUN pip3 install transformers pillow matplotlib tqdm roboflow

RUN pip3 install timm einops

RUN pip3 install flash_attn

RUN pip3 install ultralytics
RUN pip3 install pip install git+https://github.com/openai/CLIP.git
RUN pip3 install inference-gpu[yolo-world]==0.9.17
RUN pip3 install mmdet==2.28.2
RUN pip install mmdetection==3.0.0 mmengine transformers \
    pip install mmyolo

#Replacing:
#
#import onnxruntime as rt
#with
#
#import torch
#import onnxruntime as rt
#In my case the following helped:
#
#uninstall onnxruntime
#uninstall onnxruntime-gpu
#install optimum[onnxruntime-gpu]



WORKDIR /workspace

CMD ["bash"]